### ISSUE TITLE
pizzaql/pizzaql

### ISSUE THREAD

**Issue by bdougie** [bdougie/open-sauced-goals#17]
Onboard steps:

1. Fork 
2. CONTRIBUTING.md / DEVELOPMENT.md
3. Discord / Twitter / hashtag
4. npm install

|issue | status|
|- | - |
|https://github.com/graphql/graphiql/issues/571 | closed |
|https://github.com/graphql/graphiql/issues/605 | need to test with [hasura subscription example](https://github.com/hasura/graphql-engine/tree/master/community/sample-apps/react-apollo-todo)|
|https://github.com/graphql/graphiql/issues/563| need to triage|

you can triage with 
https://graphiql-test.netlify.com/

**Comment by acao** [comment]
dang this is a great idea! let me know if you need any help with bug squashing

**Comment by bdougie** [comment]
Oh hi, @acao. This is how the backend for opensauced.pizza (still WIP). 

React App to assist me in triaging potential contributions outside the project's issues.

**Comment by acao** [comment]
I see, yeah, it's a great format for planning contributions!
